version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - hooks
      - processor
      - worker

  hooks:
    build:
      context: .
      dockerfile: ./docker/hooks/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db

  processor:
    build:
      context: .
      dockerfile: ./docker/processor/Dockerfile
    depends_on:
      - db
      - kafka

  worker:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    depends_on:
      - db
      - kafka

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - db_data:/var/lib/postgresql/data

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"

volumes:
  db_data:
